export const collections = {
  users: "users",
  uploads: "uploads",
  chats: "chats",
  globalMessages: "globalMessages",
  rooms: "rooms",
  codeSnippets: "codeSnippets",
  favorites: "favorites",
  comments: "comments",
  activityLogs: "activityLogs",
  roomSubjects: "roomSubjects",
  roomTasks: "roomTasks",
  roomEvents: "roomEvents",
  notifications: "notifications",
} as const;
